### ISSUE TITLE
we can loss data pressing CONTROL + Z accidentally

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/caja#1106]
#### Expected behaviour

show dialog asking with every operations with `CONTROL + Z`

#### Actual behaviour

we can loss data pressing `CONTROL + Z `accidentally

#### Steps to reproduce the behaviour

- secondary mouse click -> create document -> empty file

- it creates an empty file with the name "new file"

- open the file "new file" (with pluma or other)

- add some text

- save the file

- go to caja and press CONTROL + Z (we can do it accidentally)

- the file is gone and we loss all of its contents

#### MATE general version

mate desktop 1.20.3

#### Package version

caja 1.20.3

#### Linux Distribution

debian testing/buster

**Comment by lukefromdc** [comment]
`CONTROL + Z` is UNDO, and should respect the default (or user set) preference "Ask before emptying trash or deleting files" and bring up the warning dialog for deleting files unless the user has that turned off.

**Comment by lukefromdc** [comment]
It looks like we have code that attempts to respect the delete confirmation here but does not actually work:

In caja-undostackmanager.c we have the function `caja_undostack_manager_undo`

containing this snippet of code:

```
        if (priv->confirm_delete) {
          caja_file_operations_delete (uris, NULL,
              undo_redo_done_delete_callback, action);
    	  g_list_free_full (uris, g_object_unref);
        } else {
          /* We skip the confirmation message
           */
          GList *f;
          for (f = uris; f != NULL; f = f->next) {
            char *name;
            name = g_file_get_uri (f->data);
            g_free (name);
            g_file_delete (f->data, NULL, NULL);
            g_object_unref (f->data);
          }
          g_list_free (uris);

```

and I found that replacing (for test purposes only) 
` if (priv->confirm_delete) {`
with
` if (priv) {` (which should always return TRUE), then we get the confirmation dialog for deleting files if and only if the user preference for asking before deleting files or emptying the trash is turned on (the default behavior). Somehow priv->confirm_delete is getting set to TRUE unconditionally. Since just using ` caja_file_operations_delete` seems to work fine and respect the user preference for the confirmation dialog, I will now write a PR for that

**Comment by lukefromdc** [comment]
Try
https://github.com/mate-desktop/caja/pull/1354

**Comment by cwendling** [comment]
Maybe Caja should *always* ask if the file changed since the operation it would undo, shouldn't it?  Using the [etag](https://developer.gnome.org/gio/stable/GFile.html#gfile-etag) should work I guess.

**Comment by sc0w** [comment]
it would be nice if in the future the killer control+z feature can be enabled/disabled by gsettings key (or remove it completely)

**Comment by lukefromdc** [comment]
I don't know enough about using etags to implement that kind of check. I could simply remove this feature entirely, but that will surely generate an issue report from someone who relies on it to clean up the mess when they accidently copy a huge number of files onto the desktop etc
