### ISSUE TITLE
Shift + Del not functioning properly

### ISSUE THREAD

**Issue by thwaller** [mate-desktop/caja#1329]
#### Expected behaviour
Using <kbd>Shift</kbd> + <kbd>Del</kbd> deletes folder or file, bypassing Trash.

#### Actual behaviour
Using <kbd>Shift</kbd> + <kbd>Del</kbd> to delete a folder or file, it seems to do this action twice. It deletes the item but then goes through the process again on the same file or folder.

I have narrowed this to Caja by following the identical process in Nautilus and PCManFM without any problem. This issue is recent, within the last month for sure.

#### Steps to reproduce the behaviour
While viewing folders and files in Caja, use <kbd>Shift</kbd> + <kbd>Del</kbd> to delete a folder or file.

#### MATE general version
1.22.2

#### Package version
1.22.2-0ubuntu1~18.04.york0

#### Linux Distribution
Ubuntu 18.04.3

#### Link to downstream report of your Distribution
??

**Comment by Zurd** [comment]
If it do make the deletion twice, so the second time you have a message saying the file doesn't exist since it deleted it on the first pass?

**Comment by thwaller** [comment]
As of MATE / Caja 1.22.3, this is no longer an issue.

It is really hard to explain what was happening. I would use <kbd>Shift</kbd> + <kbd>Del</kbd>, but then once I click on the "Delete" button in that dialog, the dialog would reappear again almost immediately. I cannot recall any further detail and it appears I was not descriptive enough in my report.

Since I no longer have the issue, nor can I reproduce it at this time, I am closing this.

**Comment by javierjosev** [comment]
**Caja version**
1.20.2-4ubuntu1

**MATE General version**
1.20.1

**MATE Package version**
1.20.1-2ubuntu1

**Linux Distribution**
Ubuntu Mate 18.04.4 LTS (Bionic Beaver) - 64-bit

Every time I press **Shift + Del** I get double confirmation dialog.
There are two exact confirmation dialog boxes, one in front of another, asking about the same delete confirmation.
If you accept the first confirmation, it deletes the item, but then goes through the process again (using the second confirmation box) on the same file or folder and of course, fails because there are no files to delete. Of course you can pres **Esc** to avoid the error.

It's really an annoying bug.

@thwaller @Zurd  can you open this issue again? This Caja version is still present on Ubuntu Mate 18.04.4 LTS

Thanks!
