### ISSUE TITLE
.desktop file renaming

### ISSUE THREAD

**Issue by FreaxMATE** [mate-desktop/caja#1371]
#### Expected behaviour
rename .desktop file correctly

#### Actual behaviour
additional .desktop suffix is appended so that the file ends with .desktop.desktop

#### Steps to reproduce the behaviour
open caja and try to rename a .desktop file

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Manjaro MATE 19.0

#### Link to downstream report of your Distribution
none

**Comment by mbkma** [comment]
I can confirm this issue.

**Comment by artebin** [comment]
Also in Caja 1.20.2 (Ubuntu and Debian), the problem exists since a long time.
I would be also a big improvement to **always** show the file extension.
Hiding the the .desktop extension because the file is executable is a non-sense, what if it exists a file with the same name without the .desktop extension?

**Comment by raveit65** [comment]
@mbkma 
PR works fine for me.

**Comment by mbkma** [comment]
@raveit65 yes, this PR fixes the problem :+1:
