### ISSUE TITLE
caja crashes when opening a folder with a jp2 file in it.

### ISSUE THREAD

**Issue by 133794m3r** [mate-desktop/caja#138]
As stated above if you have a folder with a jp2 file in it, _and_ you have ffmpeg thumbnails(I believe it's called) and attempt to open said folder caja just _crashes_. It is there, and then it's about to render the thumbnail and crash.

How to reproduce? Use image magick to convert a normal jpeg into jp2 format, watch as caja crashes whilst trying to render the thumbnail, also watch as your GPU goes into overdrive(I imagine it's still trying to render it because the file manager never told it to stop) and enjoy as you have to restart the display server to get your GPU to go back into a calmer state.

This is happening with mate 1.6, and I imagine it'll happen everywhere else too.

Edit: you also _must_ go into a terminal send a reboot command b/c nothing works, you have to send a reboot signal, and then send a halt for the system to be able to restart, b/c for whatever reason it just dies. I can attach dmesg or other such logs if you want, but I'm not very hopefull that this'll work too well.But overall this is a _crazy_ issue I don't know how hi happened or why it happened but it's nuts.

I'm on debian 7 x86 stable with mate installed, with lighdm as my dm, and also using the nvidia drivers, I am _not_ using compositing(as far as I know), and all effects are off. It tries to render that image, and POOF! everything dies. This _doesn't_ happen with kde/xfce. only mate.

**Comment by eternalbit** [comment]
Not sure, if I have the exact same issue ... running Linux Mint 17 Qiana 64bit and Caja 1.8.1. I don't notice the GPU going wild stuff and the desktop environment still works fine but the behaviour is similar ... when I open a folder containing a .jp2 file with caja it just crashes ... since caja doesn't write its ~/caja-debug-log.txt file I can't provide any more details on what happens in background.

Attached is a .jp2 file which causes caja to crash.
[jp2file.zip](https://github.com/mate-desktop/caja/files/206285/jp2file.zip)
