### ISSUE TITLE
Unable to launch symlink'ed application from Desktop

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja#1449]
#### Expected behaviour
* user is able to run symlink'ed application from Desktop

#### Actual behaviour
* user is unable to run symlink'ed application from Desktop, the following window is shown instead:

    > Could not display "/home/user/Desktop/xclock"
    > There is no application installed for shared library files. Do you want to search for an application to open this file?

   Click on Yes does not end with application launch.

Note: this is a regression, on Ubuntu MATE 16.04 LTS is works as expected.

#### Steps to reproduce the behaviour
1. Have Ubuntu MATE 20.04 LTS
2. Login to the session
3. Open terminal and create symlink to the some application executable with

   ln -s /usr/bin/xclock ~/Desktop/xclock

4. Click on just created `xclock` file symlink on the desktop

#### MATE general version
1.24

#### Package version
1.24.0-1

#### Linux Distribution
Ubuntu MATE 20.04 LTS

#### Link to downstream report of your Distribution
https://pad.lv/1877591

**Comment by lukefromdc** [comment]
This is not a problem in Caja, but rather an underlying problem where PIE (position independent Executable) binaries get mistaken by everything (file and Thunar both mentioned) for shared libraries. 
https://stackoverflow.com/questions/46551213/gcc-7-2-compiles-shared-library-instead-of-executable

Some background but little on this problem at
https://askubuntu.com/questions/690631/executables-vs-shared-objects

Nautilus report shows the bug is in  file/libmagic
https://askubuntu.com/questions/871926/impossible-to-launch-graphic-executables-in-nautilus
