### ISSUE TITLE
Build on Ubuntu MATE

### ISSUE THREAD

**Issue by r-a-cristian-93** [mate-desktop/caja#1560]
I am trying to build caja on Ubuntu MATE and i get some errors. I have already installed all the dependencies.

```
r@r-desktop:~/GitRepos/caja$ ./autogen.sh --prefix=/usr
/usr/bin/mate-autogen
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 0.29.1
checking for gtk-doc >= 1.0...
  testing gtkdocize... found 1.32
checking for mate-common >= 1.1.0...
  testing mate-doc-common... found 1.24.0
Checking for required M4 macros...
Checking for forbidden M4 macros...
Processing ./configure.ac
Running gtkdocize...
Running mate-doc-common...
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --warnings=no-portability -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --force --warnings=no-portability
autoreconf: running: automake --add-missing --copy --force-missing --warnings=no-portability
configure.ac:36: installing './compile'
configure.ac:38: installing './missing'
configure.ac:276: error: required file 'mate-submodules/Makefile.in' not found
configure.ac:276: error: required file 'mate-submodules/libegg/Makefile.in' not found
eel/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

```

**Comment by lukefromdc** [comment]
If you are building from git, you need to run 
git submodule init
folllowed by 
git submodule update

otherwise the libegg module (now a git submodule) common to many of our projects
is not included in the repo. It is maintained separately and downloaded into the 
directory you are building from with these commands

On 10/2/2021 at 6:45 PM, "r-a-cristian-93" ***@***.***> wrote:
>
>I am trying to build caja on Ubuntu MATE and i get some errors. I 
>have already installed all the dependencies.
>
>```
***@***.***:~/GitRepos/caja$ ./autogen.sh --prefix=/usr

**Comment by lukefromdc** [comment]
Reposting as email response cannot support commands:

If you are building from git, you need to run
`git submodule init`
folllowed by
`git submodule update`

otherwise the libegg module (now a git submodule) common to many of our projects
is not included in the repo. It is maintained separately and downloaded into the
directory you are building from with these commands

**Comment by r-a-cristian-93** [comment]
Thx, that fixed it!
