### ISSUE TITLE
Control Center, Screensaver Preferences: issues with Russian localization - not translated strings

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/caja#1589]
#### Expected behaviour
In "Regard the computer as idle after"
show "minute"/"minutes" and "hour"/"hours" translated to Russian: "**минуту**"/"**минут**"/"**минуты**" and "**час**"/"**часа**".

#### Actual behaviour
Regardless of region and locale this is always printed in English: "minutes" and "hour".

#### Steps to reproduce the behaviour
Open "**Control Center**", scroll to "**Look and feel**", click on "**Screensaver**"
or start from command line `mate-screensaver-preferences`.

#### MATE general version
```
mate-about --version
MATE Desktop Environment 1.22.2
```

#### Package version
```
rpm -qf /usr/bin/mate-screensaver-preferences
mate-screensaver-1.22.2-alt1.x86_64
```

#### Linux Distribution
Alt Workstation P9.2

**Comment by raveit65** [comment]
First, please become a member at Transifex server and fix russian Translation there. https://www.transifex.com/mate/MATE/dashboard/
Second, 1.22 is EOL since Feb 9, 2020. Current stable release is 1.26.
Sorry we support only one stable version as we are a small team.
When you expect a fix for old unsupported Mate versions please ask you distribution for help.
When they ship old MATE versions it is in there hand to give support.
And Distro with MATE 1.26 is fedora for example.

**Comment by HectorB-2020** [comment]
Indeed!
```
mate-about --version
MATE Desktop Environment 1.24.0

```
already contains the described translation.
