### ISSUE TITLE
Caja window looses focus after opening a file

### ISSUE THREAD

**Issue by garar** [mate-desktop/caja#1669]
#### Expected behaviour

I open a file using Caja (press enter in folder view), e.g.: a photo, and then close it, focus should return to caja window.

#### Actual behaviour

When I navigate to a file using Caja and then press enter, it opens the file in appropriate software (image viewer for images and so on). When I close the image viewer, focus doesn't return to Caja window. You can see it by the title bar color. I have to press alt+tab once to return focus back to Caja window.

I'm not sure if this is a caja bug, or a window manager bug.

#### Steps to reproduce the behaviour

1. Navigate to an image in Caja.
2. Press enter to open the image.
3. Close image viewer by pressing q.
4. Now you can see that the focus didn't return to Caja window. You can see that title bar has different color from active window.
5. Try to type something on a keyboard: foo. Normally, typing something opens quick find, in this case it won't. The window is in weird state, you can navigate using arrows in 'Icon view' but nothing works in 'List view'.

#### MATE general version

1.26.0

#### Package version

caja 1.26.0-1ubuntu1

#### Linux Distribution

Ubuntu mate 22.04

#### Link to bugreport of your Distribution (requirement)

https://bugs.launchpad.net/ubuntu-mate/+bug/1990735

**Comment by lukefromdc** [comment]
That's a known marco issue, not a caja issue. Away from my desktop so cannot easily look it up rght now

**Comment by garar** [comment]
Thanks Luke! I found some issues related to this in Marco's issue tracker. I'm closing this one.

**Comment by github-userx** [comment]
@garar I just want to thank you for bringing this up and creating this issue. (And thanks @lukefromdc for mentioning it is a Marco issue).

im just a Linux noob, very regular user but this issue has been driving me crazy on my Ubuntu-Mate 22.04 machines. I do not experience this on Ubuntu-Mate 20.04 machines.

it’s an extreme hassle for the user experience and why I haven’t upgraded one machine to 22.04 yet. (Hopefully this will be fixed in 24.04).

Unrelated but I wish Caja would be faster with handling big folder with thousands of files/folders. It can’t be hardware related because when I started Dolphin, it was able to immediately display thousands of folders and files without having to load for 10-15 seconds and getting unresponsive.

in general I’m very fond of Ubuntu-mate and the UI
