### ISSUE TITLE
MATE software are not supporting symbolic icon theme in Linux Mint 21.2

### ISSUE THREAD

**Issue by billyswong** [mate-desktop/caja#1723]
#### Expected behaviour
Support symbolic icons, and display Mint-Y themes as before

#### Actual behaviour
Mint 21.2 beta removed monotone icon images and expect software to either support symbolic icons or fallback to Adwaita. Almost everything provided by MATE is falling back, including Caja and Engrampa.

#### Steps to reproduce the behaviour
Launch Linux Mint 21.2 beta live session. Launch Caja.

#### MATE general version
MATE 1.26.0

#### Package version
Caja 1.26.0

#### Linux Distribution
Linux Mint 21.2 beta

#### Link to bugreport of your Distribution (requirement)
No. The Mint-Y theme in Mint 21.2 let software that don't support symbolic icons fallback to Adwaita icons gracefully. They are taking it as intentional behaviour.

**Comment by lukefromdc** [comment]
Icons are specified in the GTK themes and provided by the icon themes, no other support needed. We are not likely to add a set of icons to the mate or menta icon themes simply because someone deleted them from a 3ed party icon theme. If they are a problem in Cinnamon(discouraging simply reverting the commit in question,)  simply providing a "icons-extra-mate" package to add them to the icon themes when MATE is installed could be a solution.

Note that in the GTK theme it is possible to explicitly call for symbolic or regular icons, so Mint GTK themes that need these icons could specify them for the particular widgets where they are desired, using 
`-gtk-icon-style: regular` to disable symbolic icons or
`-gtk-icon-style: symbolic` to force them

When I wrote my UbuntuStudio_Legacy icon theme, I wanted to keep one particular set of symbolic icons, the ones used for the sound applet. To use them, I called them in the GTK theme with
```
/*mate-volume-control*/
/*A symbolic icon is used here and will be gray without this*/
GvcMixerDialog image{
	-gtk-icon-style: symbolic;
}
```
into the panel.css file that's part of my theme, and copied the desired icons into my matching icon theme. White symbolic volume control icons on a black panel, no sweat, with no modifications to MATE needed to support them.

Note that in css files we load for fallback theming we never override the GTK theme, the icon theme etc, we just catch cases where a widget is not being themed in a non-MATE theme

**Comment by billyswong** [comment]
I filed a bug report to https://github.com/linuxmint/mint21.2-beta/issues/54 after I found a stranger case that demonstrate the issue. The co-existence of symbolic icons, regular icons, mis-sized regular icons is bulging my eyes. There must be somebody either side or both sides did something wrong for Mint-L theme with Mint-L icon set to behave like that in Mate desktop.
![image](https://github.com/mate-desktop/caja/assets/33863356/326537f4-a016-40e0-b85e-8f898090a356)

**Comment by lukefromdc** [comment]
That's probably a mix of missing icons in Mint's icon theme and possibly issues with specifying icon types in their GTK theme. My guess is when the removed some icons from their icon theme it was only tested in Cinnamon, which although using the same GTK theme will have different widget names in such places as panel menus and thus can have different responses again depending on the theme.

Can someone using Mint test the Menta theme and icon theme together and look for any sign of this? There should be none whatsoever (I've never seen it on Debian w local builds) but if there are we need to know about it

**Comment by billyswong** [comment]
Menta in the same 21.2 beta is safe.
![image](https://github.com/mate-desktop/caja/assets/33863356/cdccdd0a-9622-48b4-a890-f6a8f2a63e0c)

**Comment by lukefromdc** [comment]
OK, that shows for sure this is a theme issue. As mint is using their own GTK and icon themes, they need to fix this

**Comment by Lurux** [comment]
@lukefromdc, just to clarify, I think this issue is about the fact that Caja is still using fullcolor icons in it toolbar and menus, instead of using symbolic icons.

In the past, Linux Mint provided monochrome icons for those applications that hadn't transitioned to symbolic icons yet, but it caused some problems with light and dark themes, so they decided to remove those in profit of old-school colorful icons.

I seem to remember Mate is purposefully aiming to maintain an more traditional look, though, so I don't expect this issue to be resolved any time soon.

___

Concerning the solution you suggested, I tried it by I adding the following line to my GTK theme: `* { -gtk-icon-style: symbolic }`, but it doesn't seem to work consistently.

- In Caja it seems to work for the most part, but the "edit" icon next to the pathbar entry doesn't get themed properly
- In Transmission, this fix doesn't work at all

Not sure if this is related to this specific theme or not, but I'll inform the Mint team about this option.

___

As far as the "mixed symbolic and fullcolor" icons go, I have no idea how this came to be, this is probably a bug in the Mint theme indeed.

**Comment by lukefromdc** [comment]
We are NOT going to switch to a "modern" look, there are plenty of other DE's for that. MATE is for those who prefer the look and feel as well as the function of GNOME 2

**Comment by Lurux** [comment]
yup, that's what I seemed to remember. Just wanted to clarify the issue and comment on the fix you suggested :slightly_smiling_face:
