### ISSUE TITLE
icons are not spoken by Orca

### ISSUE THREAD

**Issue by the-kyle** [mate-desktop/caja#245]
Running Mate 1.6.2 and Orca 3.10, the icons on the desktop and in the file manager are not being spoken by the Orca screen reader. Also, Orca is occasionally announcing that the list of icons contains 0 items, even when files are present, such as in the home directory or in the computer view. My guess is that the text of an icon as it is focused isn't getting passed to at-spi, which is the interface between the graphical toolkit and the Orca screen reader.
##

**Comment by coffeeking** [comment]
this bug no longer exists in the gtk2 version of mate and hasn't since 1.8. However, it does exist in the gtk3 version of mate. This bug has taken on a new urgency for us at the sonar project because  the gtk2 version of mate will eventually be pulled outo f the manjaro repositories, leaving the gtk3 version. I'd suggest looking at nautilus for a fix, since their icon view is accessible. You could also look at nemo, mint's fork of nautilus if you'd rather. I'll do anything I can to help.

**Comment by monsta** [comment]
@coffeeking: it seems to me that it's also discussed in https://github.com/mate-desktop/caja/issues/479 and/or https://github.com/mate-desktop/caja/issues/590. I guess we should close a report or two...

**Comment by monsta** [comment]
> Also, Orca is occasionally announcing that the list of icons contains 0 items, even when files are present, such as in the home directory or in the computer view.

This part should be fixed now with https://github.com/mate-desktop/caja/commit/68bbfd2f66682f7fcbbf4791ac685f0425a4bef5 (see https://github.com/mate-desktop/caja/pull/706 for some details).

**Comment by flexiondotorg** [comment]
I'll close this, please request a re-open if it is not completely fixed :-)
