### ISSUE TITLE
Offer a 'Preferences' option to turn off 'generic' icons in 'ListView'

### ISSUE THREAD

**Issue by uniquename999** [mate-desktop/caja#26]
FEATURE REQUEST:

   FOR NOTICEABLY BETTER PERFORMANCE of Caja in directories of thousands
   of files (and even hundreds of files), please  offer a 'Preferences' option
   to TURN OFF THE 'GENERIC' ICONS for
   directories (folders) and various file types (text, HTML, etc.)
   when the 'List View' (rather than 'Icon View') OPTION IS CHOSEN. 

   Explanation:

   A shortcoming of Nautilus/Caja (that I notice more on my netbook computers
   than on my desktop computer) is the slowness in bringing up lists of
   filenames.

   The slowness on my desktop computer is only noticed in
   navigating to directories containing more than 2,000 files (such as
   /usr/bin or /usr/lib --- about 8 to 15 seconds to show a completed filenames-list,
   the first time one opens those directories in a login session).

   Directory filename lists, for directories containing around 300 files (like
   /usr/sbin and /usr/share), appear almost instantly, on my desktop computer.

   NOT SO on netbook installations (Intel Atom or AMD C60 processor,
   running Linux Mint 11 or LMDE 201204).

   It takes about 5 or 10 seconds (or more) to display a list of about 200 filenames.

   Even though I have used the 'Edit > Preferences > Preview' path of
   Nautilus and Caja to set the options

```
* Show text in icons
* Show thumbnails
* Preview sound files 
```

   to 'Never', it takes 5-plus seconds for the directory filenames list,
   for directories containing around 300 files, to appear.

   I am pretty sure that a lot of the slowdown is due to Nautilus and Caja
   insisting on putting little icons to the left of the filenames --- such
   as folder icons and text-file icons and HTML-file icons etc. etc. (when
   'List View' is turned on).

   Those icon files (typically in /usr/share/icons subdirectories) are about
   1 Kilobyte in size, each. 

   Compare that to the 8-bits (one byte) that the  'ls -F' command uses to
   put file type indicators like \* (asterisk) and  @ (at sign) and
   / (slash) after filenames.

   It takes over 100 times the bits --- for an icon image versus a single
   ASCII character indicator.

   I would be quite happy to do without the little icons (and ASCII character
   indicators) if it would mean almost instantaneous display of large directory lists.

  The little triangle to the left of directory names is enough to indicate directories
   to me (and to allow expansion of those directories into a 'sub-list').
   I do not need the folder icons.

   And I do not need the little globe icons and page icons (etc. etc.) to
   the left of files like '.htm' and '.txt' files. I can tell the file types
   by the suffixes I gave them.

   And even if I do not provide a suffix,  I can usually tell what type of file
   it is because I created it.   (Or I can make a Nautilus/Caja Script, using
   the 'file' command, to tell me the type of a selected file.)

   So, PLEASE, Caja (and Nautilus) developers, ADD AN OPTION to the
   'Edit > Preferences > Views' panel
   --- to allow users to turn off display of ALL icons beside filenames,
for the 'List View' mode. 

  (This might even convince Xfce and LXDE desktop users to change
   to Caja and MATE.)

  An EXTERNAL REFERENCE:
  I documented this feature-request, with an image to illustrate the
  icons that I am talking about --- at

  http://www.subdude-site.com/WebPages_Local/RefInfo/Computer/Linux/LinuxMint_Installs/linuxMintDebianEdition_install_blaze.htm

This is a long page, but you can find several images that illustrate this request
by searching for the phrase 'caja performance'.
##

**Comment by lbdroid** [comment]
If showing the icon is causing a slowdown enough for the user to feel, then it it must be a matter of handling the icon incorrectly, i.e., by loading it independently for each item being listed. A directory of a thousand files probably will have files of a relatively small number of different types, so the actual number of icons loaded will be very low. Maybe 1-10 different icons.

On slower machines, it *can* take a significant amount of time just to load the file list. Comparing the time in Caja with a sorted directory listing would be more useful than just timing Caja. By the seat of my pants, on *this* machine (4-core), Caja takes about a second to load a directory with 2500 files. "time ls -l" on the same directory: "real	0m0.991s". So I'm not sure that this really would cause a significant improvement.

I still, however, would like the option to remove generic icons, but instead of showing *no* icons, have it show thumbnails like in icon view with fallback to generic icons if there are no thumbnails for the file type.
