### ISSUE TITLE
filename font color does not always get picked up from theme

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja#351]
Quoting Debian debbug#770760 [1]
:

"""
The font color of filenames in the directory listing of caja sometimes do not
get applied as they should according to the theme.

A few cases in which I have seen this happening:
  * When the BlackMATE theme has been applied. The filename font color is still
    black on the dark background, making the filenames harder to read (see the
    attached screenshot).
  * When switching from BlackMATE to a lighter theme. The filenames become
    light and thus barely readable on the white background. This is resolved
    with a restart of caja.

Strangely, this only happens in the 'icons' and 'compact' display type, not in
the 'list' display type. Switching from the 'icons' to the 'list' and back to
the 'icons' type makes the filenames the right color (light gray or white).

The 'High Contrast Inverse' theme doesn't have this problem.

(I know this could be a mate-themes bug but as the right color does get applied
under certain conditions, it seems like caja is messing up somewhere).
"""

[1] http://bugs.debian.org/770760

**Comment by Ydoow** [comment]
I have the same issue currently.

I can confirm that the issue is NOT present when using 'list' display type, and further that switching from 'icons' or 'compact' to any other view type corrects the issue temporarily.

I can also add that the colors become corrected when you remove a bookmark.

I thought it might just be the icon theme I'm using (Elementary), but switching it back to 'Ambiant Mate' gives me the same issues.

**Comment by NiceandGently** [comment]
duplicate and of  https://github.com/mate-desktop/caja/issues/81
and a regression since 1.5.x
