### ISSUE TITLE
Peculiar default view of the home directory

### ISSUE THREAD

**Issue by maandree** [mate-desktop/caja#466]
Caja has started to by default sort files and directories in my home directory by modification date and in reverse. For all other directories it is as it should be, by name and not reversed.
I am not able to reproduce this with a fresh user. The problem persist even after change, and the menu option ‘Reset View to Defaults’ changes it to these peculiar settings for the home directory, and only for the home directory.
##

**Comment by lukefromdc** [comment]
I've seen similar behavior when running Nemo or Caja as root with sudo.  In this case, configuration changes made when running as sudo are not stored and this default is what you see. You may be having a similar issue of not properly storing changes. Probably you have some kind of corrupted file in /home/<your username> because a new user does not get this, and it is preventing you from storing changes.

This sounds like a dconf issue preventing changes from being stored (assuming you are using a recent version of caja).  If the dconf database is corrupted or has wrong permissions you would get this. You could always trash the whole dconf user database and reconfigure from scratch.

**Comment by lukefromdc** [comment]
The patch below seems to stop the problem, though I will need to test for a while to be sure as this has been erattic on my systems. At the moment it seems to work great.

--- /home/luke/Desktop/caja-places-sidebar.c	2015-09-17 04:45:42.000000000 -0400
+++ /home/luke/Desktop/MATE_Development_Work/caja-1.11.0+git10072015/src/caja-places-sidebar.c	2015-10-12 00:10:13.035214803 -0400
@@ -1021,6 +1021,7 @@ over_eject_button (CajaPlacesSidebar *si
         eject_button_size = caja_get_icon_size_for_stock_size (GTK_ICON_SIZE_MENU);
 
         if (x - total_width >= 0 &&
+	    x  >= total_width - eject_button_size &&
             x - total_width <= eject_button_size) {
             return TRUE;
         }

**Comment by maandree** [comment]
This issue has now been solved.
