### ISSUE TITLE
Python extensions might cause duplicates of python-caja in extensions list

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja#520]
@alexandervdm: there's an interesting side effect visible after your fix in https://github.com/mate-desktop/caja/commit/8a826a675862d56b6d01c8467282bde9171f8cf8...

When I add more than one Python extension into ```/usr/share/caja-python/extensions/``` or ```~/.local/share/caja-python/extensions/```, a duplicate of python-caja appears in the extensions list. In other words, every Python extension, except for the first one, adds a duplicate in the list. For example, here's how it looks with 3 Python extensions added:

![caja-python-duplicates](https://cloud.githubusercontent.com/assets/5138986/13422804/253cb5d8-dfa8-11e5-89f1-6163d481684e.png)

Enabling/disabling one of these identical items enables/disables all Python extensions (it can be seen when opening the dialog next time).

**Comment by monsta** [comment]
Whoops. I forgot that in some of these VMs I had some extensions in ```~/.local/share/caja-python/extensions/``` as well. :smile:

So...
- 1 Python extension - no duplicates in the list
- 2 Python extensions - 1 duplicate
- 3 Python extensions - 2 duplicates

and so on...

**Comment by alexandervdm** [comment]
The duplicates appear because the extension management system registers the libcaja-python.so module instead of the child python extension that is loaded through that module. 

I've prepared [a commit](https://github.com/alexandervdm/caja/commit/897eec276cc2065f5ebdbb032cf5bb45a4d6f7d2) that adds a check preventing libcaja-python.so from being registered multiple times. This fixes the duplicates problem, but still does not allow python extensions from being managed individually. 

For this to happen we need to expose information like the filename of the actual python file to caja. This will require changes to both caja and python-caja. I'm working on it and aim to have this patch ready by tomorrow night.

**Comment by alexandervdm** [comment]
The two PR's referenced above fix the issue. Note that Python extensions do not expose detailed information (author, year, description and such) yet, but I'll follow up with that improvement when I can.

**Comment by monsta** [comment]
Fixed with https://github.com/mate-desktop/caja/commit/2ca207ea1a91178d28583e2bdab5c3d6aac06d87, https://github.com/mate-desktop/caja/commit/c0bfecbb6f70bc732d35b477c57d538730c358bd and https://github.com/mate-desktop/python-caja/commit/6925f41da64b5aebee5d452a40c541303dd252bf.
