### ISSUE TITLE
Middle click in bookmark menu fails

### ISSUE THREAD

**Issue by grizzler0031** [mate-desktop/caja#563]
In caja 1.12.7, when you click the middle mouse button on an item in the bookmark menu, the corresponding folder opens on a new tab. In 1.14.1 this no longer works. Nothing happens at all (except the menu closing).

System: Debian Testing 64-bit.
##

**Comment by monsta** [comment]
Probably has something to do with MATE being built with GTK+3 in Testing/Unstable now...

**Comment by raveit65** [comment]
why middle click?
left click woks well as in every menu.

**Comment by grizzler0031** [comment]
Sure, and it opens the folder on the current tab, not a new one.

**Comment by raveit65** [comment]
Btw. where is the link to downstream report.
Debian maintaner should confirm that before yo uopen a report here.

**Comment by grizzler0031** [comment]
@Vlad,
So this is the kind of "progress" GTK+3 brings? Why am I not surprised...

**Comment by monsta** [comment]
Just tested it here with latest Caja (1.17.1), built with GTK+ 3.18.9. Middle click opens the selected location in a new tab. Works not only with bookmarks, but with other places like network or trash.

**Comment by grizzler0031** [comment]
Thanks. Let's hope that by the time 1.17.1 enters Debian Testing the then current version of GTK+3 doesn't break things again... :)

**Comment by monsta** [comment]
I tested it in Debian Testing as well, it works fine there.
BTW, GTK+ 3.22 is the last release before GTK+4, so we should have some peace for a while. :smile:

**Comment by grizzler0031** [comment]
Ah yes, GTK+4. I can't wait to see what wonders _that_ will bring... 🙄

**Comment by monsta** [comment]
Lucky for us, it'll be in a separate library to avoid conflicts, and 3.22 will be supported for several years as well.

**Comment by lukefromdc** [comment]
Works fine here too with GTK 3.22.4 and caja 1.17.1: middle click on any bookmark opens it in a new tab.  GTK4 would be a major mess to port too, removing all deprecated items including several we have NOT been able to replace and probably breaking all the low level drawn stuff again due to the GSK changes. It was those changes that made GNOME branch GTK4 now, so as not to break Firefox and LIbreoffice that had just ported to GTK3.

A GTK4 port might force dropping spatial windows in caja or and would force either dropping icons in menus or adding a lot of extra code to keep them, though that code could be boilerplated, possibly using a #DEFINE  to do as much of it as possible in one place per file.  Possibly would lose custom mate-panel backgrounds, but at least any changes that broke desktop rendering would also break in in Nautilus as the code is now nearly the same in all three Nautilus-derived file managers for that other than the use of a spatial window in Caja.

It has take us two years to get GTK3 support to the point that GTK2 can be dropped, Since GTK4 goes stable in two years and then another version comes out, that would be another treadmill like GTK3 used to be but possibly worse.  Also GSK is all about OpenGL use for rendering widgets, and we might not want to go there at all as it would mess up runnng MATE on things like small ARM boards where open drivers for OpenGL do not always exist at all.  Even an old 3ed generation Intel Atom netbook with those nasty "poulsbo" GMA 500 graphics would lose out badly to replacing GTK3 with a hardware acceleration dependent or optimized GTK4.

**Comment by luigifab** [comment]
Middle click with Caja 1.26.3 and 1.28.0 does not work when you middle click on any bookmark (nothing happen), GTK 3.24.49.
