### ISSUE TITLE
Caja isn’t the File manager by default in Linux Mint MATE 18

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/caja#580]
![screenshot at 2016-07-01 19 27 07](https://cloud.githubusercontent.com/assets/3955499/16529516/abc9a9f0-3fc3-11e6-9670-a632d0e5c351.png)
See https://bugs.launchpad.net/linuxmint/+bug/1598251

**Comment by flexiondotorg** [comment]
@monsta Can you confirm? I think this issue is Mint specific and may need pursing upstream.

**Comment by raveit65** [comment]
mimetype config issue in LinuxMint?

**Comment by Petrouchka** [comment]
I added a report on https://bugs.launchpad.net/linuxmint/+bug/1598251

**Comment by monsta** [comment]
- not reproducible in Ubuntu 16.04;
- not reproducible in Ubuntu 16.10;
- reproducible in Mint 18 only once - just select Caja in the combobox and the setting will stay.

Minor distro-specific issue, another waste of time for us.

**Comment by Petrouchka** [comment]
I don't really think it's a minor bug for users not to have their file manager set as default. The file manager is the most important software, with the web browser.
I really begin to thing it's a waste of time for me to make bug reports on MATE.
And I'm not alone to think it, you should sometimes reconsider your answers.

**Comment by lukefromdc** [comment]
Distro-specific bugs often can only be fixed by the distro, an extreme case being when GTK 3.22 came out, broke caja-and Debian went on offering a broken build of Caja long after the next major version had come out with the fix. Thanks for reporting this with LinuxMint, as that's where it needs to be fixed. Ubuntu and MATE don't use (or at least did not used to use) the same builds of MATE
