### ISSUE TITLE
Unable to open locations from Places menu or folders.

### ISSUE THREAD

**Issue by Michael-AU** [mate-desktop/caja#639]
Brand new install of MATE Stretch (although this started on another install of Stretch) with no previous settings in /home to eliminate possible contamination from other installs. Go to Places click on any location, screen flashes, nothing opens.

Open a terminal (MATE terminal has also stopped working at the same time but I will report that in another report) type in caja and get
![caja-1](https://cloud.githubusercontent.com/assets/4082295/18611380/6b1d53da-7d7a-11e6-9372-c078f3fed4fe.png)

Followed suggestion from Mike Gabriel in this Debian Bug Report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778302 to no avail. Reboot machine still doesn't work.

If you want anymore info let me know and I'll get it for you.
Cheers.

**Comment by Michael-AU** [comment]
Just created a new user, to check something for another report, and this problem persists.

**Comment by lukefromdc** [comment]
What distro, caja version, and GTK version?

**Comment by lukefromdc** [comment]
Just found your problem and it's a Debian problem. Debian has updated GTK to version 3.21 so the GNOME 3.22 beta could be pulled in but didn't update MATE to its development version (1.15). As a result Caja is version 1.14.2, which segfaults with GTK 3.21 when trying to open any navigation window unless the sidebar is hidden.  Debian has completely broken MATE by updating GTK to a version MATE 1.14 does not support because it did not exist when 1.14 was released.

You could temporarily disable showing the sidebar by going to dconf-editor org>mate>caja>sidebar-panels>window-state and setting start-with-sidebar to false, except that dconf-editor has issues too in GNOME right now. If you can get dconf-editor 3.20, it will install clean and you can set this. There are instructions in other Caja issues relating to Debian for rolling back GTK 3 to version 3.20 which will make everything work again until MATE 1.16 comes out and is picked up by Debian.

We cannot fix this, Debian has to update MATE. MATE 1.16 should be out shortly, until then MATE is broken in Debian "testing" and "unstable" due to the GTK version used.
