### ISSUE TITLE
caja opens but exits from the terminal. 

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/caja#687]
See -

```
┌─[shirish@debian] - [~] - [6819]
└─[$] caja                                                                                                                          
┌─[shirish@debian] - [~] - [6820]
└─[$]   
```

Any ideas, running Debian Stretch MATE caja 1.6.1

**Comment by lukefromdc** [comment]
Try `caja /home` to see if this is an issue of caja exiting when called with no arguments. Also, if you have a build environment set up, you could try Caja 1.17.1, which uses GtkApplication instead of libunique and might behave differently in whatever situation you are getting.  I've also get a Debian package available at: 

https://archive.org/download/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme/caja-gtk3.22_1.17.1git20161122-11uke1_amd64.deb
The link will break when the package gets superseded but the replacement will be one of the many at the over site:

https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme

**Comment by kn00tcn** [comment]
according to my menu item, the file manager window is 

> caja --no-desktop --browser

**Comment by shirishag75** [comment]
Running 

`$ caja /home/$username `
`$`

works but it exists from the terminal as seen from above. 

Previously caja used to stay in the terminal console till I had not finished work on file-browser. Now whenever caja I have to run -

```
$ ps aux | grep caja 
shirish   2671  0.5  4.1 1228864 84020 ?       Sl   10:55   0:48 caja
shirish  15273  0.0  0.0  12720   932 pts/5    S+   13:21   0:00 grep --color=auto caja
```

i even tried -

```
[$] caja /home/shirish &                                                                                                         
[1] 13423

[$]                                                                                                                             
[1]  + 13423 done       caja /home/shirish
```

I'm running mate 1.16.1 

```
[$] caja --version                                                                                                               
MATE caja 1.16.1
```
 
As shared above, now the behavior has changed, it works but exits in the terminal. I like the old behaviour  :(

**Comment by kn00tcn** [comment]
i'm not sure what you want to do or did do that requires it to be in the terminal console

but what happens if you use **--no-desktop** and/or **--browser** as part of the command??

**Comment by lukefromdc** [comment]
In both 1.16(linunique) and 1.17(GtkApplication), invoking Caja while it is already running (such as managing the desktop) passes any arguments it is called with to the existing process.  With GtkApplication such an invocation passes its arguments to the exiting process, which then opens the Caja navigation (or spatial) window. The second invocation then exits, thus the terminal returns to the command line. 

The window stays open, as it was opened by the FIRST process which received the arguments from the command line. If no arguments were given, caja defaults to opening the user's home directory. This is intentional and goes back to when libunique was first used to force all invocations of Nautilus to a single process, probably so the session manager could more easily be set to remember all open windows if so desired but possibly for other reasons.

Given that Nautilus abandoned the session saving code and computers today are usually multi-core, I'm a bit surprised GNOME devs didn't cut Nautilus loose from the single-process model, which is easily done by having GtkApplication set "application-id" to "NULL" as was done in Engrampa. This would mean a crash in one instance of Nautilus would not take down another instance that was say, copying a big batch of files.  Doing this in Caja however would complicate session saving, as only one instance would have been autostarted and others would not be saved.

**Comment by kn00tcn** [comment]
does that mean caja wont gain multi process windows without a large rewrite?

i dont use session saving so maybe a dconf option would be nice if gtkapplication is allowing multi process so far

**Comment by lukefromdc** [comment]
I certainly do not have the skills to do that kind of rewrite. You could put each invocation in its own process as explained above but that's it.  You will run into a chicken and egg situation trying to control this with dconf though, as the values would have to be read before "caja_application_new" is run in caja-application.c . A similar problem interfered with setting session management to "no_restart, with no solution but to disable session management when running from the command line or as root. This in turn would mean that splitting off all the later caja invocations into their own processes would always block saving their session state.  Thus this change could not be made always-on either unless session saving was to be scrapped. Session saving is a feature we want to keep.

To multi-thread the main process would be an utter rewrite and totally beyond me. Keep in Mind, Nautilus dates from the Pentium 4 era when computers without two CPU sockets had one core, one thread.  Even GNOME has not rewritten Nautilus for multithreading. Keep in mind, I have no formal training in this and am entirely self-taught.  If this sort of thing were so easy the GTK3 port would not have taken two years to get to a releasable state.

Nautilus began as the sole project of an entire corporation (Easel) that folded when it was done. Probably their plans to monetize it as the front-end to paid servers (thus remote server support from the start) was simply not viable. Not only is MATE not a paid team of paid programmers, even GNOME probably does not have the kind of resources Easel did for the short time they were in existance.

**Comment by kn00tcn** [comment]
well, one obvious solution is to drop the file manager as part of the caja process & have it standalone (or rename one of them)... in fact right now i'm trying out pcmanfm on xfce & i'm liking it more than thunar or caja

**Comment by lukefromdc** [comment]
The desktop is just a special case of the file manager window (a spatial Window in Caja/Nautilus before 3.0). Nautilus has now split out a separate binary for the desktop-but mostly for their wayland work and because they don't like the desktop at all. It was a substantial refactoring and cannot be directly applied to Caja as a very large number of files had been moved around into different directories before that time.

Most MATE users are probably quite satisified with the desktop/panel paradigm, if this was not true they would be on GNOME 3, Unity, or something else. I don't see MATE screwing with it.

**Comment by lukefromdc** [comment]
BTW, if you want to play with a split-out desktop you can do it this way: set Caja not to draw icons on the desktop (desktop>background>show-desktop-icons=false), then run an instance of nautilus-desktop, xfce-desktop, or whichever desktop manager you prefer. You won't see any performance difference, you'd do this to combine different features.

**Comment by shirishag75** [comment]
Hi all, 

Very very interesting discussion here. While @lukeefromdc has hit it on the head squarely, still this is something I would like to see (if we can at some time regain the feature )

```
> pcmanfm                                                                                                                          [95%]
** Message: x-terminal-emulator has very limited support, consider choose another terminal

** (pcmanfm:18595): WARNING **: XDG_TEMPLATES_DIR is set to invalid path, ignoring it
```

While granted there are issues with pcmanfm still it works I hate caja when it exits so in case caja crashes there is no way to know why it crashed. If it were under the console/terminal then at least there would be something that could be used to report if and when things go wrong. Hope this makes it clear. 

And running caja through gdb is not something I can do every time.

**Comment by monsta** [comment]
As it's been explained, the behavior is normal.
