### ISSUE TITLE
Search results should use the same view settings as the folder being searched [$65]

### ISSUE THREAD

**Issue by politas** [mate-desktop/caja#704]
I have my default folder view set to icon view. There is one folder that I use list view in, and I regularly need to search in it (it contains files with hash codes prepended for programmatic searching).

Every time I enter search details, caja resets to icon view. I really need to see the date modified on these results, so I have to change the view every time.

Search results should use the same view choice as the folder being searched.

**Comment by meequz** [comment]
I think search results should always be shown in list view, no matter what user prefers for usual folder view. More than that, column "Location" should be enabled by default in search results, because you can get a lot of similar items and obviously you want to know location of each of them.

How it looks like now by default in Ubuntu MATE:
![search results inconvenient view](https://user-images.githubusercontent.com/2832374/38681044-78827524-3e70-11e8-86ec-566929ee8b3d.png)

How I think it would be comfortable for all the users:
![search results handy view](https://user-images.githubusercontent.com/2832374/38681189-d0308eaa-3e70-11e8-881a-f5fefe8b0a21.png)

**Comment by politas** [comment]
Perhaps there could be an option to override folder view setting for searches that allows the user to specify what they want search results to look like, if they don't want to accept the current folder's options? I think the default should definitely be to use the current folder's display settings.

**Comment by hbregalad** [comment]
In addition to defaulting to list view, the location field should be visible when in search view. To my knowledge the location field is useless outside search view, and 90% or more of my use cases for search the contents of location field is the entire point either to read and learn where my files got to, or to differentiate all the different files with the same name.

**Comment by politas** [comment]
I've added another $50 to the bounty for this.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja/commit/27ca0ac7e6b73b1c633674d119f03a8e19dcd3fd

I hope this is sufficient for the bounty.
