### ISSUE TITLE
Sidebar shows an entry for "Desktop" instead of username when XDG_DESKTOP_DIR="$HOME"

### ISSUE THREAD

**Issue by elcste** [mate-desktop/caja#714]
I don't use the desktop folder, so I deleted the folder and set `XDG_DESKTOP_DIR="$HOME"` in `~/.config/user-dirs`. When this is the case, the Caja sidebar top entry shows up as "Desktop" instead of my username. The "Go" menu still shows "Home Folder" and no Desktop entry. I installed Nautilus, and it shows an entry for "Home" in both cases.

(Ubuntu MATE 16.10, Caja 1.16.0)

**Comment by flexiondotorg** [comment]
All you're doing is changing to path to what is labelled the Desktop. Also, if you enable "show desktop icons" everything in your home directory will now be visible on the desktop.

**Comment by elcste** [comment]
Yes, I understand these two points. I don't use the Desktop, so I have the icons hidden anyway. My real feature request is to be able to delete some of these folders that I don't use, such as ~/Desktop and ~/Videos, and remove them from the sidebar.

**Comment by flexiondotorg** [comment]
Caja requires a 'Desktop' folder. As for removing other folders, then you can learn more with `man user-dirs.default` :-)

If you edit `/etc/xdg/user-dirs.conf` and change `enabled=True` to `enabled=False`, that will stop the default XDG directories being created at login. You can the remove what you don't want from your home directory. You will probably need to purge some of the Caja dconf tree to remove the links to the default directories in the sidebar.

But we are getting into the realms of user support here :-) So, I'll close this, since we're not going to remove the requirement for Caja to have a desktop folder, but you've got some clue to customise your desktop :-)

**Comment by elcste** [comment]
Fair enough. I concede that most people using MATE probably use the desktop. Thanks for your consideration.

I don't know how much you charge as a consultant ;-) but I just sent an extra £20 to Ubuntu MATE in appreciation. I had stumbled on some of it, but not /etc/xdg/user-dirs.conf, and I will check out the man page.

**Comment by flexiondotorg** [comment]
Very kind, thank you ☺️

**Comment by elcste** [comment]
FWIW, this was reported again (and likely better explained!) as https://github.com/mate-desktop/caja/issues/813 and is now fixed in 1.20!
