### ISSUE TITLE
Caja two-finger, touchpad, scrolling broken in Compact View 

### ISSUE THREAD

**Issue by galik** [mate-desktop/caja#801]
#### Expected behaviour

In Caja window, two fingers on touchpad scroll left or right in Compact View

#### Actual behaviour

Only scrolls right

#### Steps to reproduce the behaviour

1. Set touchpad to left/right scrolling
```bash
synclient VertTwoFingerScroll=1
synclient HorizTwoFingerScroll=1
```
2. Select Compact View (Menu->View->Compact)
3. Try to scroll sideways using touchpad
#### MATE general version

From 1.16 - 1.18

#### Package version

From: caja-1.16.2-1.fc25.x86_64
To: caja-1.18.3-1.fc25.x86_64
(and counting)
#### Linux Distribution

Fedora 25

Bug registered with Fedora in February:
https://bugzilla.redhat.com/show_bug.cgi?id=1426130

[Originally posted to mate-desktop](https://github.com/mate-desktop/mate-desktop/issues/271)

**Comment by galik** [comment]
Some additional info. Looking back in my package manager history I discovered the bug ppeared between these versions:
```
caja-1.16.1
caja-1.16.2
```
I have isolated what I believe may be the code change in question being here:
```
src/file-manager/fm-icon-view.c
```
It could be this commit:
```
commit d773ac2760052190cccb7ca1161a005fb2464b7d
Author: lukefromdc <lukefromdc@hushmail.com>
Date:   Thu Nov 3 23:31:30 2016 -0400

    GTK+3: fix mousewheel scrolling in compact view
    
    with patch by ZenWalker to fix horizontal wheel scrolling
    
    cherry-picked and squashed from:
    https://github.com/mate-desktop/caja/commit/f34590dd7a71251515b90cd9812878b7d26d30b6
    https://github.com/mate-desktop/caja/commit/ae053dbf2cc26ae74df5e782261c3a3bc7126763
    https://github.com/mate-desktop/caja/commit/3e93f938000cdb24a6137daecd77fe010ae93f36
```

**Comment by lukefromdc** [comment]
Reverting that breaks mousewheel scrolling. I don't know how to do touchpad scrolling and the only laptop I own is a tiny netbook.  I normally scroll only with mousewheels or scrollbars so its no wonder I never saw that.

Who here is familiar with touchpad scrolling and can work on this?

If it works in one direction that should be a clue to the other. Since the offending commit came from Nautilus, there may also be a corrosponding Nautilus commit relating to this.

**Comment by galik** [comment]
I have just compiled `Caja v1.18.3` after reverting that code portion to the `1.16.1` version and I can confirm that fixes `Caja` on my system. So something about that code doesn't work for my setup.

```
    description: Notebook
    product: HP Pavilion 15 Notebook PC (F2U56EA#ABU)
    vendor: Hewlett-Packard
    version: 0883100000305B10000620100
    serial: 5CD33959W9
    width: 64 bits
    capabilities: smbios-2.7 dmi-2.7 smp vsyscall32
    configuration: boot=normal chassis=notebook family=103C_5335KV G=N L=CON B=HP S=PAV X=Null sku=F2U56EA#ABU uuid=35434433-3339-3539-5739-A0481C2114AA
```

**Comment by lukefromdc** [comment]
Someone else will have to work on this as I have no way to test it. @monsta ? @raveit65 ? @clefebvre ?

**Comment by raveit65** [comment]
I will do and see if i can reproduce it on my notebook.
@galik 
For your info, with the 1.18 update i switched to use libinput driver instead of using synaptics in fedora.
libinput driver support was a major improvement with 1.18.
This shouldn't be related as your test shows that it was a prob with 1.16.x too,
With using libinput it is possible to use gnome-shell again with a touchpad on a multiuser system.
Those guys have dropped using old synaptics driver from their suite.
MATE can use boths ;-)
For this reason i switched to libinput for f25 during a release cycle.
For the record, those commands should show the new driver.
xinput --list
xinput --list-props <id of you touchpad device >

**Comment by monsta** [comment]
I still don't have a laptop, so I can only test if #803 doesn't break the fix from #674 for the mousewheel.

**Comment by raveit65** [comment]
Btw. the synclient command is obsolete, you can remove the synaptics driver.

**Comment by raveit65** [comment]
Ok, with my MSI FX700 + fedora 26 + libinput driver i can confirm that 2-finger scrolling is broken in compact-view. It works in general with using list-view.
But if my mouse cursor is over the scrollbar (not touched) 2 finger-horz-scrolling is working with the touchpad.
Now testing the PR.......

**Comment by raveit65** [comment]
@sc0w 
Huston we have a problem...
