### ISSUE TITLE
Can't eject removable media without loading listing

### ISSUE THREAD

**Issue by unkilbeeg** [mate-desktop/caja#880]
#### Expected behaviour
Click on sidebar eject button next to media icon and media is unmounted

#### Actual behaviour
Click on sidebar eject button next to media icon and the current view in the listing pane is replaced with the listing of that particular media.  A second click on the eject button will eject the media.

#### Steps to reproduce the behaviour
Launch  Caja with the file listing on your home directory (or any directory, really.)  Plug in usb drive or CD or any other removable medium.  Click on the eject button next to the icon for your removable medium and instead of ejecting, the listing changes to that of the medium you're trying to eject.  Normally the listing already showing is something I'm using -- I don't want it to shift just because I've ejected something else.

I did a search and ran across the following fixed bug:
https://github.com/mate-desktop/caja/issues/472?_pjax=%23js-repo-pjax-container
This bug involved ejecting any time you selected the icon of the mounted medium.  My problem is the opposite -- I want a portion of that field to be available to immediately eject. It looks like both issues come from the entire field being treated as one entity -- clicking on it used to cause an immediate eject, and now it causes an immediate load of the file pane.  I'd like it to work where the right side (the eject button) works to eject the medium and the left side (the icon for the filesystem) acts to load a file listing. 

#### MATE general version
Package: mate-common
Version: 1.18.0-1+sonya

#### Package version
Package: caja
Version: 1.18.5-1+sonya

#### Linux Distribution
Linux Mint 18.2

**Comment by lukefromdc** [comment]
No matter how I fiddle with the coding for the over_eject_button function in caja-places-sidebar.c, I will always get either an occasional unwanted unmount or an occasional unwanted open rather than unmount. It looks like I can make this a bit less touchy about being over the eject button itself but I think there is a race condition between something else and over_eject_button returning.

Sometimes Caja will even first go to the root directory of the volume being unmounted, then unmount it. The code in Nemo works, but has a long string of changes and a simple attempt to apply the bulk of the changes for position sensing
https://github.com/GNOME/nautilus/commit/f294a4e80626793624d76d6002b094d1c0809de4
led to unconditional mount./umount no matter where in the drive's row the mouse was clicked. Will investigate further.

This comment from the aboce GNOME commit "Due to a bug in Gtk which expands the eject icon cell renderer we have to right align it so that it lines up properly." explains another issue: if the sidebar is made REALLY wide, the eject icon gets padded away from the right edge of the column and the eject column becomes too wide. With the current coding that disables ejection outright, so I will have to fix that at least.

**Comment by lukefromdc** [comment]
Try
https://github.com/mate-desktop/caja/pull/881
and see if that helps. It certainly made ejecting less "fiddly" here

**Comment by lukefromdc** [comment]
OK, it looks like https://github.com/mate-desktop/caja/pull/881 does not fix the underlying cause of this, though it solves the problem of many (as in more than two) clicks often needed to eject a drive when the sidebar is a bit wide.  

I just found that clicking exactly on the icon usually ejects the drive cleanly, while clicking on the treeview's row near but not directly over the icon will sometimes eject the drive cleanly and sometimes display the contents of the directory on first click, then eject on the second click. That is probably a race condition somewhere.

**Comment by sc0w** [comment]
I don't know why, but I can't reproduce the issue here, with caja 1.18.5 (debian testing, gtk 3.22.26)

video:

[out-54.ogv.zip](https://github.com/mate-desktop/caja/files/1553243/out-54.ogv.zip)

**Comment by lukefromdc** [comment]
All of these problems (directory switch instead of eject and difficult ejection) are influenced by the width of the sidebar. Resize the sidebar to something much wider than normal and see what happens

**Comment by sc0w** [comment]
@lukefromdc aha, yes, I can confirm the issue now, here the eject button doesn't work with the side bar wider

**Comment by lukefromdc** [comment]
If you try https://github.com/mate-desktop/caja/pull/881 you should find you can now eject no matter how wide you make the sidebar, and won't accidently eject unless the sidebar is very wide and you click on that row past the end of all the text on all the listed items. Beyond that is the eject column it seems.

**Comment by lukefromdc** [comment]
I just managed to successfully apply the far neater Nemo/Nautilus code for eject click handling, will push it as an update to https://github.com/mate-desktop/caja/pull/881

**Comment by lukefromdc** [comment]
Just redid https://github.com/mate-desktop/caja/pull/881
with the Nautilus/Nemo code, and I was no longer able to reproduce this. Clicking near the eject icon (but not on it) now changes to the device's root directory, clicking on the icon itself ejects it without changing the directory. No accidental unmounts seem possible, and all the old hardcoded kludges for this are gone.
