### ISSUE TITLE
Missed scroll for tab bar

### ISSUE THREAD

**Issue by Lbif-RU** [mate-desktop/caja#896]
Starting with Fedora 25 and Linux Mint 18.2 in Caja lost a scroll on the tab bar. This is the only way to switch the active tab when Caja is not in the active window.
![caja](https://user-images.githubusercontent.com/35063022/34649764-f1f42052-f400-11e7-8c93-3814138b0484.png)

**Comment by ericek111** [comment]
I also find this very annoying. It was one of the features I loved. It used to work in Ubuntu MATE 16.04, but when mate-desktop migrated to GTK+3, it was removed. I'll try to reimplement it back.

Some more info:
https://bugs.launchpad.net/midori/+bug/1210159
https://bugzilla.gnome.org/show_bug.cgi?id=145244

**Comment by sc0w** [comment]
It works in caja 1.8.2 (gtk2) and I confirm it doesn't work here with caja 1.21.2

**Comment by mp107** [comment]
I can confirm the issue.
In Ubuntu MATE 16.04.6 I was able to switch between tabs (not windows) in Caja file manager (v. 1.12.7) by pointing moving the cursor on tabs list and roll the mouse wheel but on Ubuntu MATE 18.04.2 I cannot do it this way.
I asked about a problem [in the thread on Ubuntu MATE Community](https://ubuntu-mate.community/t/looking-for-a-way-to-switch-between-tabs-using-mouse-wheel-in-caja-file-manager-on-ubuntu-mate-18-04-2/19494) and was directed here.
#### Expected behaviour
Pointing mouse on the tab bar of the Caja file manager one can use mouse wheel to switch between opened tabs.

#### Actual behaviour
Pointing mouse on the tab bar of the Caja file manager it is not possible to use mouse wheel to switch between opened tabs.

#### Steps to reproduce the behaviour
1. Open Caja file manager window.
2. Open at least one more tab in the window.
3. Scroll mouse wheel while pointing the cursor over tabs bar. Tabs are not changing.

#### MATE general version
- Manjaro MATE 18.0.4 - 1.22.0-1
- Ubuntu MATE 18.04 - 1.20.1

#### Package version
- Manjaro MATE 18.0.4 - Caja - 1.22.0-1
- Ubuntu MATE 18.04 - Caja - 1.20.2-4ubuntu1

#### Linux Distribution
##### Problem not exists on:
- Ubuntu MATE 16.04.6
##### Problem exists on:
- Manjaro MATE 18.0.4
- Ubuntu MATE 18.04

**Comment by N0rbert** [comment]
Modern versions are also affected:

* Caja 1.20.2 as in Ubuntu MATE 18.10;
* Caja 1.20.3 as in Ubuntu MATE 19.04.

**Comment by sc0w** [comment]
all the caja versions since gtk3 are affected

**Comment by N0rbert** [comment]
Reported to launchpad as https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1839539 .

**Comment by lukefromdc** [comment]
That launchpad bug should probably stay open until Ubuntu releases a package with the fix, which might require a backport unless Ubuntu wants to wait for 1.24

**Comment by lukefromdc** [comment]
Oh yeah-I just saw (and confirmed) that the mentioned PR did not include that particular set of tabs(main navigation window tabs).

**Comment by N0rbert** [comment]
Still problem for Caja 1.24 as in upcoming Ubuntu MATE 20.10.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/1422
fixes this but is only in git master (currently at 1.25) meaning distros don't get it until either MATE 1.26 is released or someone cherrypicks or if necessary backports it to 1.24

**Comment by ericek111** [comment]
Five years later, it's still INCREDIBLY annoying to not be able to scroll in all GTK apps. It's like GNOME devs are anti-usability. I'm starting to hate the crap they're pulling -- the libadwaita cancer, broken accessibility, no customizability, monochromatic non-descript icons, messed up inconsistent title bars. I feel like Linux desktop was in a better state 15 years ago than it is now. I just keep coming to these old issues... Very frustrating. Makes me feel like I'm using Windows.

Sorry, rant over. I love MATE a lot. <3

This has been solved for a while. Let's close it.
