### ISSUE TITLE
Index files "index.theme" behaviour

### ISSUE THREAD

**Issue by MDykstra** [mate-desktop/caja#91]
In **"~/.theme/some-theme/"** the **"index.theme"** is shown by its **"Name"** field, as specified inside the **"index.theme"**. Right-clicking on the file does not allow to edit the **"index.theme"** file by selecting pluma. Copying a **"index.theme"** file to another theme folder, thereby replacing an existing **"index.theme"** file, renames the **"index.theme"** file to something else.
##

**Comment by NiceandGently** [comment]
related fixes for nautilus are here:
https://git.gnome.org/browse/nautilus/commit/?h=gnome-3-4&id=b9c51fd4eb84a9f52ee4be1bf183fc516984130b
https://git.gnome.org/browse/nautilus/commit/?id=c1551df
https://bugzilla.gnome.org/show_bug.cgi?id=319981
https://bugzilla.gnome.org/show_bug.cgi?id=672809
But code is too different from nautilus to apply them,
but maybe this helps to find a fix for caja.

**Comment by erikdubois** [comment]
strange that this issue is not yet resolved. As an icon theme designer I have the need to change this file.
Linux Mint 18 Cinnamon and 18.1 open such a file with any editor you like. In mate we get an error.
![index](https://cloud.githubusercontent.com/assets/10594806/21294665/648c0a6a-c542-11e6-90b0-c5e80006e66e.png)
I resolve it now by opening e.g. sublime text and drag/drop index.theme on sublime text to open it.

**Comment by raveit65** [comment]
I tried again to apply the commits from nautilus. They apply now but i get an error with open the file.
![bildschirmfoto zu 2016-12-18_20-12-53](https://cloud.githubusercontent.com/assets/961604/21295860/719fbad2-c55e-11e6-8dc7-a3c4ea7cdb69.png)
Resulting patch is here https://gist.github.com/raveit65/19cfc5fe706ac6a2ea5d663a94fb02af

**Comment by lukefromdc** [comment]
It seems to me that mimetype "theme(application-x-theme) should be treated as a text file by Caja. Obviously Caja it is trying to open these with something else with this patch, no idea what that application is as no text gets sent to terminal if started from there.  Just removing the code that hides the right-click menu for .desktop files might help-and also would make it easier to edit launchers without having to drag and drop them into Pluma

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/694
Unconditionally shows the right-click "open with" menu for all files except directories. Desktop files launch as before on left-click or can be opened with text editors from the right-click menu, same as in Nemo. Theme files will still generate an error on left-click as they are not executable but now can be opened from the right-click menu in Pluma.

The other needed change to match Nemo's behavior is to recognize theme files as text rather than executable files so far as Caja is concerned.

**Comment by raveit65** [comment]
> Theme files will still generate an error on left-click as they are not executable but now can be opened from the right-click menu in Pluma.

Which right click menu in pluma?
I just tested the PR but i do not see what is fixed?

**Comment by lukefromdc** [comment]
The "open with" item in the right-click menu is normally not shown for certain file types, including directories, .desktop files-and those theme files. My PR shows it for all file types except directories

**Comment by lukefromdc** [comment]
Point I was making was "can be opened in Pluma, from the right-click menu in Caja,"  NOT from a menu in Pluma itself.

**Comment by raveit65** [comment]
I asked because i do not have the option open with with your PR.
Let us talk there.

**Comment by lukefromdc** [comment]
You may have just found a bug in my PR, not sure where it came from as the original experimental build worked, then a build from the branch give the results you reported. I will now look for a difference in the files.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/694
has been considerably updated, shows the right-click menu and "open with" tab in properties but it looks like index.theme files are being treated as desktop launchers, thus overriding any application set as default. Previously it seems they were being treated as directories, which is also wrong

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/caja/commit/5432a415dadbd8db34081037645e0c38457900ec
https://github.com/mate-desktop/caja/commit/a4f26d060486684e8d37e922ab2fbc4dcc02a85e
https://github.com/mate-desktop/caja/commit/91dcd8a19665b6738f8304db127f45b503e00ce3
and cherry-picked to 1.16 branch.
