### ISSUE TITLE
spatial windows doesn't work

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/caja#969]
I don't know if this was already reported, I think this is a very old issue

#### Expected behaviour

open folders in new windows with the option in preferences

this is an old nautilus screenshot with the behavior:

![expected_spatial_windows](https://user-images.githubusercontent.com/7734191/38219908-26725ad2-36d8-11e8-924a-30143449cdc7.png)

#### Actual behaviour

the option doesn't work

#### Steps to reproduce the behaviour

This checkbox is useless:

![image823](https://user-images.githubusercontent.com/7734191/38219710-28634e9c-36d7-11e8-83b5-9a860f9236fe.png)

#### MATE general version

1.20.0

#### Package version

1.20.0-2 and 1.8.2 (debian jessie vm gtk2)

#### Linux Distribution

debian testing

seems the code with that behavior is here:

https://github.com/mate-desktop/caja/blob/master/src/caja-spatial-window.c

**Comment by lukefromdc** [comment]
I just tested this, and the option works fine here (on Debian Unstable) except for one thing: To open something in a spatial window it must itself be opened FROM a spatial window. The desktop is always a spatial window, and opening a folder from the desktop with this option selected opens it in a spatial window rather than the normal navigation (browser) window. Close all your navigation windows after setting this option, and you will see only spatial windows unless you deliberately open a navigation window by running caja --browser from terminal or the panel run dialog.

An existing navigation window does not turn into a spatial window when this option is changed, so it continues to behave as a normal navigation window, and any new windows spawned from it will also be navigation windows. I think this is deliberate and intentional behavior to support the --browser (open a browser window) option  and ensure that it works correctly. I remember doing a considerable amount of work during the GtkApplication port of Caja to ensure that this part of Caja's behavior worked the same way it had worked before with libunique.

**Comment by sc0w** [comment]
@lukefromdc aha, yes, it needs to close all the windows, ok

time to try with the deprecated GtkImageMenuItem there :)

**Comment by lukefromdc** [comment]
You don't actually need to CLOSE all the navigation windows, as new windows from the desktop or terminal will open in spatial windows with this option selected regardless of how many navigation windows are still showing or opened with --browser. You just don't get a spatial window from a navigation window ever, they come from other spatial windows such as the desktop, or from windows newly opened from something other than caja (e.g.terminal). That's why I suggested closing all the existing navigation windows, to remove a source of confusion.

**Comment by sc0w** [comment]
ok, thanks for the detailed explanations :+1:
