### ISSUE TITLE
Need a means to distinguish desktop from other windows via ATK/AT-SPI2

### ISSUE THREAD

**Issue by joanmarie** [mate-desktop/caja#999]
I (the Orca screen reader maintainer) have been asked to prevent Orca from saying "frame" (or "window") when users give focus to the Desktop. But it is still desirable for Orca to say "frame" (or "window") when users switch into a true frame/window. In order to accomplish this I need some way to be able to distinguish the Desktop from true windows using AT-SPI2.

The problem is that as far as AT-SPI2 is concerned, the Desktop is just another top-level accessible container with role "frame" (i.e. it looks like another, proper window). One solution that occurred to me is to look at the frame's bounding box. After all, most true windows don't occupy the full screen. That said, some true windows have a full-screen mode. So even this approach is not 100% reliable.

Perhaps the addition of an AtkObject attribute might be the way to go. You can pretty much add any attribute as a name:value pair. So one could hypothetically do "is-desktop" for the name and "true"/"false" for the value. Then all Caja windows should have the value of "false" (or just lack the attribute completely) with the exception of the Desktop non-window which would have "true".

I'm open to other ideas if someone has a better suggestion. Thanks!

**Comment by alexarnaud** [comment]
@joanmarie Thank you for filing this bug. I found your last proposal really reasonable. Do you thin adding the property "is-desktop" to true for desktop and noting for other window could be sufficient ?

Do you plan to work on this ? Hypra could work on this bug because most of our users are impacted by this issue.

@sthibaul What is your opinion on this ?

Best regards,
A Lex.

**Comment by joanmarie** [comment]
@alexarnaud: My plan right now would be to use the result in Orca, but not to implement the change in Caja itself. This is a nice-to-have; not a super-critical must-have (like fixing the event floods). And I have fewer spare cycles for the next month or so.... That said, hopefully it will be quite easy to make the change in Caja, assuming what I describe is acceptable to the Caja maintainers. So Hypra tackling it sounds good to me.

In answer to your other question, the absence of "is-desktop" is the same thing (as far as I'm concerned) as  "is-desktop" being present but set to false. As long as the actual desktop -- and no other top-level accessible object, including a window showing the contents of the desktop -- has "is-desktop" set to true, it should be sufficient for my needs.

**Comment by alexarnaud** [comment]
@joanmarie Thank you for your answer. 

Keep in mind that Hypra wouldn't work on event flood because most of our users doesn't have big folder and we've more criticize bug to figure out before. I personally would like to see the event flood fixed but my personal needs and the needs of Jean-Philippe and others advanced users but we need to focus on low-vision stuff primarily because we're the only one to work on.

Best regards,
Alex.

**Comment by alexarnaud** [comment]
@joanmarie We'll fix this bug in the next month, I hope a little bit before but it will depend of the complexity of the others bugs in our TODO :).

Best regards,
Alex.

**Comment by alexarnaud** [comment]
@lukefromdc Could it be possible to backport this for 1.20?

Best regards,
Alex.

**Comment by lukefromdc** [comment]
Backported with
https://github.com/mate-desktop/caja/commit/ba087de8c7a9f1a4b93fdc74d917465dd2d89eb0
after testing with Orca (outputting to a logfile due to speech-dispatcher problems on my setuo).

**Comment by alexarnaud** [comment]
@lukefromdc Thank you very much for the backport, it will really improve the UX of blind and low-vision users :).

Best regards,
Alex.

**Comment by lukefromdc** [comment]
Glad to help, accessability should be a high priority (as it was in GNOME 2) as it helps keep people independent.
